[package]
name = "console-utils"
version = "1.5.0"
edition = "2021"
authors = ["Nils Wrenger <nils@wrenger.net>"]
description = "Cli input utilities."
keywords = ["console", "terminal", "cli"]
categories = ["command-line-utilities", "cli"]
repository = "https://github.com/nwrenger/console-utils-rs"
readme = "README.md"
license = "MIT"

[lib]

[target.'cfg(unix)'.dependencies.libc]
version = "0.2.150"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_SystemServices"
]
