[package]
name = "console-utils"
version = "1.4.0"
edition = "2021"
authors = ["Nils Wrenger <nils@wrenger.net>"]
description = "Cli input utilities."
keywords = ["console", "terminal", "cli"]
categories = ["command-line-utilities", "cli"]
repository = "https://github.com/nwrenger/console-utils-rs"
readme = "README.md"
license = "MIT"

[lib]

[dependencies]
console = "0.15.7"
