[package]
name = "console-utils"
version = "1.5.0"
edition = "2021"
authors = ["Nils Wrenger <nils@wrenger.net>"]
description = "Cli input utilities."
keywords = ["console", "terminal", "cli"]
categories = ["command-line-utilities", "cli"]
repository = "https://github.com/nwrenger/console-utils-rs"
readme = "README.md"
license = "MIT"

[lib]

[dependencies]
termios = { version = "0.3.3", default-features = false }
winapi = { version = "0.3.9", features = ["winuser"] }
